import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>God Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/coder.ico" />
      </Head>
      <main className={styles.main}>



        <div className={styles.center}>
          <h1>God Coder</h1>
        </div>

        <div>
          <img src="/coder.png" alt="" height={200} width={200} style={{ marginBottom: '2rem' }} />
        </div>

        <div className={styles.description}>
          <p>
            Coder never quits, They try and become successful
          </p>
        </div>

        <div className={styles.blogs}>
          <div className={styles.blogitem}>
            <h3>Set clear goals</h3>
            <p>
              Setting goals helps to give you direction and focus.
            </p>
          </div>
          <div className={styles.blogitem}>
            <h3>Focus on the process, not just the end result</h3>
            <p>
              Focuses on the process of learning and improving your coding skills.
            </p>
          </div>
          <div className={styles.blogitem}>
            <h3>Find a coding mentor or role model</h3>
            <p>
              Look for successful coders who you admire and try to learn from them.
            </p>
          </div>
        </div>
      </main>
    </>
  )
}
